version: '3.9'
services:
  config-server:
    image: image-config-server:v1
    ports:
      - "8088:8088"
    restart: always
    networks:
      - spring-cloud-network
  discovery-service:
    image: image-discovery-service:v1
    ports:
      - "8061:8061"
    restart: always
    networks:
      - spring-cloud-network
    depends_on:
      - config-server
  gateway-service:
    image: image-gateway-service:v1
    ports:
      - "8060:8060"
    restart: always
    networks:
      - spring-cloud-network
    depends_on:
      - discovery-service
  service-bus:
    image: image-service-bus:v1
    ports:
      - "8001:8001"
    restart: always
    networks:
      - spring-cloud-network
    depends_on:
      - discovery-service
  service-tasador:
    image: image-service-tasador:v1
    ports:
      - "8002:8002"
    restart: always
    networks:
      - spring-cloud-network
    depends_on:
      - discovery-service
networks:
  spring-cloud-network: